# Generated by Django 5.0.6 on 2024-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=10000)),
                ("create_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "day",
            },
        ),
    ]
